A throw statement exit from a method and so on and so on or it is caught by a try/catch block. It does not return a variable but an exception:<br /><br /><br /><br />Code section 3.20: A return statement.<br /><br /><br />1     public int getAge() {<br />2         throw new NullPointerException();<br />3     }<br /><br /><br /><br /><br />Beware not to write statements after a throw statement which would not be executed too! Each throw statement is ended by a semi-colon (;).