try is a keyword.<br />It starts a try block. If an Exception is thrown inside a try block, the Exception will be compared any of the catch part of the block. If the Exception match with one of the Exception in the catch part, the exception will be handled there.<br />Three things can happen in a try block:<br /><br />No exception is thrown:<br /><br />the code in the try block<br />plus the code in the finally block will be executed<br />plus the code after the try-catch block is executed<br /><br /><br />An exception is thrown and a match is found among the catch blocks:<br /><br />the code in the try block until the exception occurred is executed<br />plus the matched catch block is executed<br />plus the finally block is executed<br />plus the code after the try-catch block is executed<br /><br /><br />An exception is thrown and no match found among the catch blocks:<br /><br />the code in the try block until the exception occurred is executed<br />plus the finally block is executed<br />NO CODE after the try-catch block is executed<br /><br /><br /><br />For example:<br /><br /><br /><br /><br /><br /><br />public void method() throws NoMatchedException<br /> {<br />   try {<br />     //...<br />     throw new '''MyException_1'''();<br />     //...<br />   } catch ( MyException_1 e ) {<br />     // --- '''Handle the Exception_1 here''' --<br />   } catch ( MyException_2 e ) {<br />     // --- Handle the Exception_2 here --<br />   } finally {<br />     // --- This will always be executed no matter what --<br />   }<br />   // --- Code after the try-catch block<br /> }<br /><br /><br /><br /><br />How the catch-blocks are evaluated see Catching Rule<br />See also:<br /><br />Java Programming/Keywords/catch<br />Java Programming/Keywords/finally<br />Java Programming/Throwing and Catching Exceptions#Catching Rule